Housekeeping
- Standardize dependency checks
- Standardize OS checks

Signed-off-by: Joe Block <jpb@unixorn.net>

diff --git a/bin/clip b/bin/clip
--- a/bin/clip
+++ b/bin/clip
@@ -1,11 +1,32 @@
 #!/bin/bash
 #
 # clipboard helper
+#
+# Copyright 2016-2025 Joe Block <jpb@unixorn.net>
+#
+# License: Apache 2.0
 
 if [[ "$(uname -s)" != 'Darwin' ]]; then
   echo 'Sorry, this script only works on macOS'
   exit 1
 fi
+
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
+
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
+  fi
+}
+
+check-dependency pbcopy
 
 # shellcheck disable=SC2071
 if [[ $# > 0 ]]; then
diff --git a/bin/do-not-disturb b/bin/do-not-disturb
--- a/bin/do-not-disturb
+++ b/bin/do-not-disturb
@@ -2,20 +2,41 @@
 #
 # Stifle notifications
 #
-# Copyright 2017, Joe Block <jpb@unixorn.net>
-
+# Copyright 2017-2025, Joe Block <jpb@unixorn.net>
+#
+# License: Apache 2.0
+#
 # Turn off Apple notifications.
 #
 # Based on an answer by Jacques Rioux  on discussions.apple.com.
 #
 # https://discussions.apple.com/thread/7520296?start=0&tstart=0
 
-if [[ "$(uname -s)" != 'Darwin' ]]; then
-  echo 'Sorry, this script only works on macOS'
-  exit 1
-fi
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
+
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
+  fi
+}
+
+function only-run-on() {
+  if [[ "$(uname -s)" != "$1" ]]; then
+    fail "This script only runs on $1"
+  fi
+}
+
+only-run-on Darwin
+check-dependency defaults
 
 now=$(date -u "+%Y-%m-%dT%TZ")
 defaults -currentHost write com.apple.notificationcenterui doNotDisturb -bool TRUE
 defaults -currentHost write com.apple.notificationcenterui doNotDisturbDate -date "$now"
-osascript -e 'quit application "Notification Center"'
+exec osascript -e 'quit application "Notification Center"'
diff --git a/bin/dump-entitlements b/bin/dump-entitlements
--- a/bin/dump-entitlements
+++ b/bin/dump-entitlements
@@ -14,10 +14,26 @@ IFS=$'\n\t'
 # This makes bash consider newlines and tabs as separating words
 # See: http://redsymbol.net/articles/unofficial-bash-strict-mode/
 
-if [[ "$(uname -s)" != 'Darwin' ]]; then
-  echo 'Sorry, this script only works on macOS'
-  exit 1
-fi
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
+
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
+  fi
+}
+
+function only-run-on() {
+  if [[ "$(uname -s)" != "$1" ]]; then
+    fail "This script only runs on $1"
+  fi
+}
 
 function usage {
   echo
@@ -33,7 +49,6 @@ function usage {
   exit 0
 }
 
-
 ### Utility Functions ###
 # ctrl_c
 
@@ -44,31 +59,26 @@ function ctrl_c {
 
 ### END Utility Functions ###
 
-
 function find_binaries {
   # find_binaries
 
   sudo --prompt="[⚠️ ] sudo required to search everywhere" -v
-
   sudo find / -type f -exec file {} \; -print | grep 'Mach-O' | awk -F ':' '{print $1}' > "${BINARIES_FILENAME}"
 }
-
 
 function dump_entitlements {
   # dump_entitlements
 
   while read binary; do
-    /usr/bin/codesign --display --entitlements - "${binary}" 2>&1 > "${ENTITLEMENTS_FILENAME}"
+    codesign --display --entitlements - "${binary}" 2>&1 > "${ENTITLEMENTS_FILENAME}"
   done < "${BINARIES_FILENAME}"
 }
-
 
 function sort_entitlements {
   # sort_entitlements
 
   awk '{print $2}' "${ENTITLEMENTS_FILENAME}" | grep com.apple | sort -u > "${SORTED_ENTITLEMENTS_FILENAME}"
 }
-
 
 function main {
 
@@ -107,5 +117,8 @@ function main {
       ;;
   esac
 }
+
+only-run-on Darwin
+check-dependency codesign
 
 main "$@"
diff --git a/bin/finder-path b/bin/finder-path
--- a/bin/finder-path
+++ b/bin/finder-path
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright 2015 Joseph Block <jpb@apesseekingknowledge.net>
+# Copyright 2015-2025 Joseph Block <jpb@apesseekingknowledge.net>
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -14,14 +14,36 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-if [[ "$(uname -s)" != 'Darwin' ]]; then
-  echo 'Sorry, this script only works on macOS'
-  exit 1
-fi
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
+
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
+  fi
+}
+
+function only-run-on() {
+  # shellcheck disable=SC2086
+  if [[ "$(uname -s | tr '[:upper:]' '[:lower:]')" != "$(echo $1 | tr '[:upper:]' '[:lower:]')" ]]; then
+    fail "This script only runs on $1, this machine is running $(uname -s)"
+  else
+    debug "OS ($(uname -s)) is valid..."
+  fi
+}
+
+only-run-on darwin
+check-dependency osascript
 
 # Print the path to the frontmost Finder window
 
-osascript <<EOT
+exec osascript <<EOT
   tell application "Finder"
     if (${1-1} <= (count Finder windows)) then
       get POSIX path of (target of window ${1-1} as alias)
diff --git a/bin/fix-airplay b/bin/fix-airplay
--- a/bin/fix-airplay
+++ b/bin/fix-airplay
@@ -2,19 +2,39 @@
 #
 # Airplay sometimes craps out, add helper to kick it
 #
-# Copyright 2016, Joe Block <jpb@unixorn.net>
+# Copyright 2016-2025, Joe Block <jpb@unixorn.net>
 
 set -o pipefail
 
-if [[ "$(uname -s)" != 'Darwin' ]]; then
-  echo 'Sorry, this script only works on macOS'
-  exit 1
-fi
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
+
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
+  fi
+}
+
+function only-run-on() {
+  # shellcheck disable=SC2086
+  if [[ "$(uname -s | tr '[:upper:]' '[:lower:]')" != "$(echo $1 | tr '[:upper:]' '[:lower:]')" ]]; then
+    fail "This script only runs on $1, this machine is running $(uname -s)"
+  else
+    debug "OS ($(uname -s)) is valid..."
+  fi
+}
 
 if [[ "$(whoami)" != 'root' ]]; then
-  echo 'This script must be run by root or with sudo'
-  exit 1
+  fail 'This script must be run by root or with sudo'
 fi
+
+only-run-on darwin
 
 # shellcheck disable=SC2009
 exec kill "$(ps -ax | grep '/usr/sbin/coreaudiod' | awk '{print $1}')"
diff --git a/bin/keychainctl b/bin/keychainctl
--- a/bin/keychainctl
+++ b/bin/keychainctl
@@ -4,10 +4,32 @@
 
 KEYCHAIN=${KEYCHAIN:-"secrets.keychain"}
 
-if [[ "$(uname -s)" != 'Darwin' ]]; then
-  echo 'Sorry, this script only works on macOS'
-  exit 1
-fi
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
+
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
+  fi
+}
+
+function only-run-on() {
+  # shellcheck disable=SC2086
+  if [[ "$(uname -s | tr '[:upper:]' '[:lower:]')" != "$(echo $1 | tr '[:upper:]' '[:lower:]')" ]]; then
+    fail "This script only runs on $1, this machine is running $(uname -s)"
+  else
+    debug "OS ($(uname -s)) is valid..."
+  fi
+}
+
+only-run-on darwin
+check-dependency security
 
 main () {
   if [[ -z "$1" ]]; then
diff --git a/bin/macos-major-version b/bin/macos-major-version
--- a/bin/macos-major-version
+++ b/bin/macos-major-version
@@ -1,14 +1,37 @@
 #!/usr/bin/env bash
 #
-# Copyright 2020, Joe Block <jpb@unixorn.net>
+# Copyright 2020-2025, Joe Block <jpb@unixorn.net>
 #
 # macOS has a habit of changing the way it does some of its non-posixy things
 # every major rev or so. Add a helper to standardize detecting the rev
 
 set -o pipefail
-if [[ "$(uname -s)" != 'Darwin' ]]; then
-  echo 'Sorry, this script only works on macOS'
-  exit 1
-fi
 
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
+
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
+  fi
+}
+
+function only-run-on() {
+  # shellcheck disable=SC2086
+  if [[ "$(uname -s | tr '[:upper:]' '[:lower:]')" != "$(echo $1 | tr '[:upper:]' '[:lower:]')" ]]; then
+    fail "This script only runs on $1, this machine is running $(uname -s)"
+  else
+    debug "OS ($(uname -s)) is valid..."
+  fi
+}
+
+only-run-on darwin
+check-dependency sw_vers
 sw_vers -productVersion | awk -F '.' '{print $1 "." $2}'
+exit $?
diff --git a/bin/macos-notification b/bin/macos-notification
--- a/bin/macos-notification
+++ b/bin/macos-notification
@@ -2,7 +2,7 @@
 #
 # Display a notification on macOs
 #
-# Copyright 2021, Joe Block <jpb@unixorn.net>
+# Copyright 2021-2025, Joe Block <jpb@unixorn.net>
 
 set -o pipefail
 
@@ -15,34 +15,55 @@ usage(){
   echo "   $(basename $0) notificationTitle subTitle soundName text"
 }
 
-if [[ "$(uname -s)" = "Darwin" ]]; then
-  if [[ $# -eq 1 ]]; then
-    message_command="display notification \"$1\""
-    exec osascript -e "$message_command"
-  fi
+function echo-stderr() {
+  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
+}
 
-  if [[ $# -eq 2 ]]; then
-    message_command="display notification \"$2\" with title  \"$1\""
-    exec osascript -e "$message_command"
-  fi
+function fail() {
+  echo-stderr "$1"
+  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
+}
 
-  if [[ $# -eq 3 ]]; then
-    message_command="display notification \"$3\" with title  \"$1\" subtitle  \"$2\""
-    echo "message_command: $message_command"
-    exec osascript -e "$message_command"
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+    fail "Missing dependency: can't find $1 in your PATH"
   fi
+}
 
-  if [[ $# -eq 4 ]]; then
-    message_command="display notification \"$4\" with title  \"$1\" subtitle  \"$2\" sound name  \"$3\""
-    echo "message_command: $message_command"
-    exec osascript -e "$message_command"
+function only-run-on() {
+  # shellcheck disable=SC2086
+  if [[ "$(uname -s | tr '[:upper:]' '[:lower:]')" != "$(echo $1 | tr '[:upper:]' '[:lower:]')" ]]; then
+    fail "This script only runs on $1, this machine is running $(uname -s)"
+  else
+    debug "OS ($(uname -s)) is valid..."
   fi
+}
+
+only-run-on darwin
+check-dependency osascript
+
+if [[ $# -eq 1 ]]; then
+  message_command="display notification \"$1\""
+  exec osascript -e "$message_command"
+fi
+
+if [[ $# -eq 2 ]]; then
+  message_command="display notification \"$2\" with title  \"$1\""
+  exec osascript -e "$message_command"
+fi
+
+if [[ $# -eq 3 ]]; then
+  message_command="display notification \"$3\" with title  \"$1\" subtitle  \"$2\""
+  echo "message_command: $message_command"
+  exec osascript -e "$message_command"
+fi
+
+if [[ $# -eq 4 ]]; then
+  message_command="display notification \"$4\" with title  \"$1\" subtitle  \"$2\" sound name  \"$3\""
+  echo "message_command: $message_command"
+  exec osascript -e "$message_command"
+fi
 
 # shellcheck disable=SC2068
-  usage $@
-  exit 1
-else
-  # shellcheck disable=SC2086
-  echo "$(basename $0) only works on macOs"
-  exit 1
-fi
+usage $@
+exit 1
