Housekeeping
- Update dependency checking in many scripts

Signed-off-by: Joe Block <jpb@unixorn.net>

diff --git a/bin/darktoggle b/bin/darktoggle
--- a/bin/darktoggle
+++ b/bin/darktoggle
@@ -8,6 +8,14 @@ function fail() {
   exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
 }
 
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+      error "missing dependency: can't find $1 in your PATH"
+      exit 1
+  fi
+}
+check-dependency osascript
+
 if [[ "$(uname -s)" = "Darwin" ]]; then
   read -d '' darktoggle << EOR
 tell application "System Events"
diff --git a/bin/enable-bouncing-dock-icons b/bin/enable-bouncing-dock-icons
--- a/bin/enable-bouncing-dock-icons
+++ b/bin/enable-bouncing-dock-icons
@@ -2,14 +2,26 @@
 #
 # Enable bouncing dock icons
 #
-# Copyright 2020, Joe Block
+# Copyright 2020-2025, Joe Block
 
 set -o pipefail
 
-if [[ "$(uname -s)" != 'Darwin' ]]; then
-  echo 'Sorry, this script only works on macOS'
-  exit 1
-fi
+function only-run-on() {
+  if [[ "$(uname -s)" != "$1" ]]; then
+    echo "This script only runs on $1"
+    exit 1
+  fi
+}
+
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+      error "missing dependency: can't find $1 in your PATH"
+      exit 1
+  fi
+}
+
+only-run-on Darwin
+check-dependency defaults
 
 defaults write com.apple.dock no-bouncing -bool FALSE
 killall Dock
diff --git a/bin/install-latest-chrome b/bin/install-latest-chrome
--- a/bin/install-latest-chrome
+++ b/bin/install-latest-chrome
@@ -9,6 +9,14 @@ if [[ "$(uname -s)" != 'Darwin' ]]; then
   exit 1
 fi
 
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+      error "missing dependency: can't find $1 in your PATH"
+      exit 1
+  fi
+}
+check-dependency hdiutil
+
 # Checking if Chrome is running
 if pgrep "Google Chrome" > /dev/null
 then
diff --git a/bin/iterm b/bin/iterm
--- a/bin/iterm
+++ b/bin/iterm
@@ -51,6 +51,14 @@ COMMAND="cd $WD"
 TITLE="$1"
 COLOR="$2"
 
+function check-dependency() {
+  if ! (builtin command -V "$1" >/dev/null 2>&1); then
+      error "missing dependency: can't find $1 in your PATH"
+      exit 1
+  fi
+}
+check-dependency osascript
+
 echo "Launching iTerm with COMMAND: $COMMAND TITLE: $TITLE COLOR: $COLOR $EXIT"
 
 osascript 2>/dev/null <<EOF
diff --git a/bin/mergepdfs b/bin/mergepdfs
--- a/bin/mergepdfs
+++ b/bin/mergepdfs
@@ -22,5 +22,14 @@ if [[ $# -eq 0 ]]; then
   exit 0
 fi
 
+function check-dependency() {
+    if ! (builtin command -V "$1" >/dev/null 2>&1); then
+        error "missing dependency: can't find $1"
+        exit 1
+    fi
+}
+
+check-dependency /System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py
+
 # shellcheck disable=SC2068
 /System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py $@
