Generate an mpeg if `ffmpeg` is installed
Closes #4

Signed-off-by: Joe Block <jpb@unixorn.net>

diff --git a/bin/screencap-stream b/bin/screencap-stream
--- a/bin/screencap-stream
+++ b/bin/screencap-stream
@@ -2,7 +2,7 @@
 #
 # screencap-stream
 #
-# Captures a stream of PNGs to a directory
+# Captures a stream of PNGs to a directory. If we find ffmpeg, we then render them to .mp4
 #
 # Copyright 2022, Joe Block <jpb@unixorn.net>
 
@@ -39,7 +39,7 @@ function on_exit()
 {
     for i in "${on_exit_items[@]}"
     do
-        eval $i
+        eval "$i"
     done
 }
 
@@ -52,21 +52,24 @@ function add_on_exit()
     fi
 }
 
-# Set up a working scratch directory
-SCRATCH_D=$(mktemp -d)
-
-if [[ ! "$SCRATCH_D" || ! -d "$SCRATCH_D" ]]; then
-  echo "Could not create temp dir"
-  exit 1
-fi
-
-function _cleanup()
+function makemovie()
 {
-  echo "In cleanup"
-  rm -rf "$SCRATCH_D"
+  echo "Creating movie from frames in $target_d"
+  echo "You set the interval between frame captures to $interval, setting movie rate to ${hertz}hz"
+  cd "$target_d" || fail "Couldn't change to $target_d"
+  ffmpeg -pattern_type glob -framerate "$hertz" \
+    -i "*.png" \
+    -c:v libx264 \
+    -r 30 \
+    -pix_fmt yuv420p \
+    -movflags +faststart \
+    screencap.mp4
 }
-# add_on_exit rm -rf "$SCRATCH_D"
-add_on_exit _cleanup
+
+if has ffmpeg; then
+  echo "Found ffmpeg, will make a movie after screen frames are captured."
+  add_on_exit makemovie
+fi
 
 if ! has screencapture; then
   fail "Cannot find 'screencapture' in your PATH."
@@ -78,15 +81,19 @@ fi
 
 target_d="$1"
 interval="$2"
+raw="scale=0; 1 / $interval / 4" # Was too fast until I halved the speed as a fudge factor
+hertz=$(bc <<< "$raw")
 
 debug "target_d: $target_d"
 debug "interval: $interval"
+debug "hertz: $hertz"
 
 if [[ ! -d "$target_d" ]]; then
   fail "$target_d is not a directory"
 fi
 
 while :; do
-  echo "📸 $(date +%H:%M:%S)"; screencapture -x $target_d/$(date +%s).png
+  echo "📸 $(date +%H:%M:%S)"
+  screencapture -x "$target_d/$(date +%s).png"
   sleep "$interval"
 done
